package org.asl.common.propertyparser;

public enum PropertyKey {
	USER,
	PASSWORD,
	PORT,
	MIDDLEWARE_IP,
	MIDDLEWARE_PORT,
	DATABASE_IP,
	DATABASE_PORT,
	DATABASE_NAME,
	NUM_ASYNC_CONNECTION_POOL_THREADS,
	CONTENT_LENGTH,
	MAX_CONNECTIONS_TO_DB,
	INITIAL_BUFSIZE
}