package org.asl.common.timing;

public enum Timing {
	CLIENT_START_REQUEST,
	CLIENT_SENT_REQUEST,
	CLIENT_READ_ANSWER,
	CLIENT_PROCESSED_ANSWER,
	MIDDLEWARE_ACCEPTED_CLIENT,
	MIDDLEWARE_READ_REQUEST,
	MIDDLEWARE_PROCESSED_READ,
	MIDDLEWARE_GOT_CONNECTION,
	MIDDLEWARE_EXECUTED_QUERY,
	MIDDLEWARE_PACKED_REQUEST,
	MIDDLEWARE_WROTE_ANSWER
}
