package org.asl.common.timing;

public enum Timing {
	CLIENT_START_CONNECT,
	CLIENT_END_CONNECT,
	CLIENT_START_WRITE,
	CLIENT_END_WRITE,
	CLIENT_START_READ,
	CLIENT_END_READ,
	CLIENT_START_POSTPROCESSING,
	CLIENT_END_POSTPROCESSING,
	MIDDLEWARE_START_READ,
	MIDDLEWARE_END_READ,
	MIDDLEWARE_START_PROCESSING,
	MIDDLEWARE_GOT_CONNECTION,
	MIDDLEWARE_START_QUERY,
	MIDDLEWARE_END_QUERY,
	MIDDLEWARE_START_COMMIT,
	MIDDLEWARE_END_COMMIT,
	MIDDLEWARE_END_PROCESSING,
	MIDDLEWARE_START_WRITE,
	MIDDLEWARE_END_WRITE,
}
