package org.asl.common.timing;

public enum Timing {
	CLIENT_START_WRITE, // 0
	CLIENT_END_WRITE, // 1
	CLIENT_START_READ, // 2
	CLIENT_END_READ, // 3
	CLIENT_START_POSTPROCESSING, // 4
	CLIENT_END_POSTPROCESSING, // 5
	MIDDLEWARE_START_READ, // 6
	MIDDLEWARE_END_READ, // 7
	MIDDLEWARE_START_PROCESSING, // 8
	MIDDLEWARE_GOT_CONNECTION, // 9
	MIDDLEWARE_START_QUERY, // 10
	MIDDLEWARE_END_QUERY, // 11
	MIDDLEWARE_START_COMMIT, // 12
	MIDDLEWARE_END_COMMIT, // 13
	MIDDLEWARE_END_PROCESSING, // 14
	MIDDLEWARE_START_WRITE, // 15
	MIDDLEWARE_END_WRITE // 16
}
